### PR TITLE
⬆️: Upgrade Expo SDK to 45

### PR DESCRIPTION
**Pull request by creature-water-valley**
## ✅ What's done
 
- [x] `expo upgrade 45`
  - [Changelog](https://github.com/expo/expo/blob/main/CHANGELOG.md#4500--2022-04-25)
  - Since React Native Elements depends on the react-native-safe-area-context 3.x, only react-native-safe-area-context is left as 3.3.2
- [x] Apply changes of [expo-template-bare-minimum](https://github.com/expo/expo/commits/sdk-45/templates/expo-template-bare-minimum)
- [x] Apply changes of [ReactNativeFlipper.java](https://github.com/facebook/react-native/commits/0.68-stable/template/android/app/src/debug/java/com/helloworld/ReactNativeFlipper.java)
- [x] Add patch for React Native Elements type error 
- [x] Fix lint error(flatten of AnimatedStyle and ViewStyle) 
- [x] Update snapshots 
- [x] Fix autoCompleteType in TextInputProps changed to autoComplete.
- [x] Fix AppState cleanup
- [x] Fix SelectPickerItems test to use useFakeTimers and runAllTimers
- [x] Add option `requireConfirmation` to local authentication demo
- [x] Add eslint-plugin-deprecation to detect deprecated 
- [x] Set "EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "" 
- [x] Add ResetEditText to styles.xml
- [x] Bump up macOS  to 12 and Xcode to 13.3.1 on ci to resolve the following errors
  - `❌  ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1316.0.21.2.3_0' Reader: '1300.0.29.30_0')', using libLTO version 'LLVM version 13.0.0, (clang-1300.0.29.30)' for architecture arm64`
  - Similar ref. https://github.com/expo/eas-cli/issues/1079
- [x] Remove cache pods restorekeys on c
- [x] Remove cleanBuildCache from android cmd in reset-cache
- [x] Bump up tool versions
    | Tool | from | to |
    |-----|-----|----|
    | Node.js | 16.14.2 | 16.15.1 |
    | Ruby | 3.0.3 | 3.1.2 |

---

## Tests

- [x] `npm run ios` and `npm run android` for all build variants
- [x] Run all lanes of fastlane

以下のコマンドのいずれかをこのプルリクエストのコメントとして投稿すると、
Azure Pipeline上でSantokuAppをビルドしてDeployGateへアップロードできます。
4種全てのビルドバリアントを対象にする場合はdeploy-all、
特定のビルドバリアントだけを対象にする場合はdeploy-ビルドバリアント名のコマンドを利用してください。

- /azp run deploy-all
- /azp run deploy-devSantokuAppDebugAdvanced
- /azp run deploy-devSantokuAppReleaseInHouse
- /azp run deploy-santokuAppDebugAdvanced
- /azp run deploy-santokuAppReleaseInHouse

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] iOS
  - [x] シミュレータ (iPhone 13/iOS 15)
  - [x] 実機 (iPhone 8/iOS 15)
- [ ] Android
  - [x] エミュレータ (Pixel 4a/Android 12)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

If NewArchitecture is enabled, iOS will have a build error.

### CODE REVIEW

**Comment by creature-water-valley** [comment]
- /azp run deploy-all

**Review by in-a-paddy — APPROVED** [review]

**Review by a-mtn595COMPETIZIONE — APPROVED** [review]

**Pull request merged**
